name: Workflow with multiple stages that go in order

on: push

jobs:
  job-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: get the date
        run: date
      - run: pwd
  job-on-windows:
    name: A Job that runs on windows
    runs-on: windows-latest
    steps:
      - name: first step on windows job
        run: date
      - run: ls 

  dependant-on-job1:
    needs: [job-on-ubuntu, job-on-windows]
    runs-on: macos-latest
    name: A job that runs on mac after first tow
    steps:
      - run: pwd
      - run: ls
      
    
